name: Shopify Theme Deployment

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      
      - name: Theme Check
        run: shopify theme check theme/
        
  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: theme-check
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
        
      - name: Deploy to development theme
        run: shopify theme push --store=${{ secrets.SHOPIFY_STORE_URL }} --theme=${{ secrets.SHOPIFY_DEV_THEME_ID }} --path=theme/
        env:
          SHOPIFY_CLI_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: theme-check
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
        
      - name: Deploy to production theme
        run: shopify theme push --store=${{ secrets.SHOPIFY_STORE_URL }} --theme=${{ secrets.SHOPIFY_PROD_THEME_ID }} --path=theme/
        env:
          SHOPIFY_CLI_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
